#!/usr/bin/env bash

PREFIX=$1
PDF="$PREFIX/pad"
PROGRAM="$PREFIX/tests/simple/program.c"
#TARGET="$PREFIX/tests/simple/target.c"
PID=$$
SYMBOL="breakpoint"
ACTION="LOAD"

echo "$PDF --PROGRAM $PROGRAM --TARGET $TARGET --SYMBOL $SYMBOL --ACTION $ACTION"
$PDF --PROGRAM $PROGRAM --TARGET_PID $PID --SYMBOL $SYMBOL --ACTION $ACTION
